HRS/HRS/Models/MakeAnAppointment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRS.Models
{
    public class MakeAnAppointment
    {
        public int Id { get; set; }
        public int ClinicId { get; set; }
        public int DoctorId { get; set; }
        public int TimeId { get; set; }
        public DateTime TransactionDate { get; set; }
    }
}

HRS/HRS/Controllers/MakeAnAppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HRS.Models;
using Microsoft.Data.SqlClient;

namespace HRS.Controllers
{
    public class MakeAnAppointmentController : Controller
    {
        private string _connection = @"Data Source = HP\SQLEXPRESS; Initial Catalog = HRS; User ID = sa; Password = 123456; Integrated Security = True";
        HRS.DataContext.HrsContext hrsContext = new DataContext.HrsContext();

        public IActionResult Index()
        {
            var viewmodel = new HRS.ViewModel.MakeAnAppointmentViewModel
            {
                clinics = hrsContext.GetClinics()
            };
            return View(viewmodel);
        }

        [HttpPost]
        public IActionResult Clinic(int id)
        {
            var doctors = hrsContext.GetDoctorList(id);
            return Json(doctors);
        }

        [HttpPost]
        public IActionResult Appointment(int id)
        {
            var times = hrsContext.GetTime(id);
            return Json(times);
        }

        [HttpPost]
        public IActionResult Add(HRS.ViewModel.MakeAnAppointmentViewModel makeAnAppointment)
        {
            using (SqlConnection sqlConnection = new SqlConnection(_connection))
            {
                sqlConnection.Open();

                

                string query = "INSERT INTO PatientAppointments(ClinicId,DoctorId,TimeId,TransactionDate) VALUES (@p1,@p2,@p3,@p4)";

                SqlCommand sqlCommand = new SqlCommand(query, sqlConnection);

                sqlCommand.Parameters.AddWithValue("@p1", makeAnAppointment.ClinicId);
                sqlCommand.Parameters.AddWithValue("@p2", makeAnAppointment.DoctorId);
                sqlCommand.Parameters.AddWithValue("@p3", makeAnAppointment.TimeId);
                sqlCommand.Parameters.AddWithValue("@p4", makeAnAppointment.TransactionDate);

                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");

        }
    }
}

HRS/HRS/Views/MakeAnAppointment/Index.cshtml
@model HRS.ViewModel.MakeAnAppointmentViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom red-bg page-heading">
    <div class="col-lg-10">
        <h2>Randevu Al Sayfası</h2>
        <ol class="breadcrumb red-bg">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index","Home")">Anasayfa</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Randevu Al</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">

        <div class="doctor-list"></div>

        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Randevu Alma Formu</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    @using (Html.BeginForm("Add", "MakeAnAppointment", FormMethod.Post))
                    {
                        <select class="form-control m-b Cliniz-Select" name="ClinicId">
                            <option>---- Klinik Seçiniz ----</option>
                            @foreach (var item in Model.clinics)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                        <select class="form-control m-b Doctor-Select" name="DoctorId" id="doctor-option">
                            <option>---- Doktor Seçiniz ----</option>
                        </select>
                        <label id="times-list">

                        </label>
                        <div class="hr-line-dashed"></div>
                        <div class="col-sm-4 col-sm-offset-2">
                            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-floppy-o"></i> Kaydet</button>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>