HRS/HRS/Controllers/ClinicController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using HRS.Models;
using System;
using System.Collections.Generic;

namespace HRS.Controllers
{
    public class ClinicController : Controller
    {
        private string _connection = @"Data Source = HP\SQLEXPRESS; Initial Catalog = HRS; User ID = sa; Password = 123456; Integrated Security = True";

        HRS.DataContext.HrsContext hrsContext = new DataContext.HrsContext();
        public IActionResult Index()
        {
            var viewmodel = new HRS.ViewModel.ClinicViewModel
            {
                Clinics = hrsContext.GetClinics()
            };
            return View(viewmodel);
        }

        [HttpPost]
        public IActionResult Add(Models.Clinic clinic)
        {
            if (string.IsNullOrEmpty(clinic.Name))
            {
                TempData["title"] = "Boş";
                return RedirectToAction("Index");
            }
            else
            {
                using (SqlConnection sqlconnection = new SqlConnection(_connection))
                {
                    sqlconnection.Open();

                    string name = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(clinic.Name);

                    string query = "INSERT INTO Clinic VALUES ('" + name + "')";

                    SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                    sqlCommand.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            using (SqlConnection sqlconnection = new SqlConnection(_connection))
            {
                sqlconnection.Open();

                string query = "DELETE FROM Clinic WHERE Id = '" + id + "'";

                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
    }
}

HRS/HRS/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HRS.Models;
using Microsoft.Data.SqlClient;

namespace HRS.Controllers
{
    public class DoctorsController : Controller
    {
        HRS.DataContext.HrsContext hrsContext = new DataContext.HrsContext();
        public IActionResult Index()
        {
            var viewmodel = new HRS.ViewModel.DoktorsViewModel
            {
                workerAndDoctors = hrsContext.GetDoctors(),
                Clinics = hrsContext.GetClinics()
            };
            return View(viewmodel);
        }

        [HttpPost]
        public IActionResult Add(Models.Doctors doctors)
        {
            string con = @"Data Source = HP\SQLEXPRESS; Initial Catalog = HRS; User ID = sa; Password = 123456; Integrated Security = True";

            using (SqlConnection sqlconnection = new SqlConnection(con))
            {
                sqlconnection.Open();

                string query = "INSERT INTO Doctors VALUES ('" + doctors.WorkerId + "','" + doctors.ClinicId+ "','" + doctors.Rank+ "','"+doctors.Status+"')";

                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
    }
}

HRS/HRS/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using HRS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace HRS.Controllers
{
    public class RolesController : Controller
    {
        string connection = @"Data Source = HP\SQLEXPRESS; Initial Catalog = HRS; User ID = sa; Password = 123456; Integrated Security = True";
     
        public IActionResult Index()
        {
            var roles = new List<Models.Roles>();

            using (SqlConnection sqlconnection = new SqlConnection(connection))
            {
                sqlconnection.Open();

                string query = "SELECT * FROM Roles ORDER BY Id DESC";

                SqlCommand sqlCommand = new SqlCommand(query,sqlconnection);

                using (SqlDataReader sqlDataReader = sqlCommand.ExecuteReader())
                {
                    while (sqlDataReader.Read())
                    {
                        var role = new Roles();
                        role.Id = Convert.ToInt32(sqlDataReader["Id"]);
                        role.Name = sqlDataReader["Name"].ToString();

                        roles.Add(role);
                    }
                }
            }
            var viewmodel = new HRS.ViewModel.RolesViewModel
            {
                Role = roles
            };
            return View(viewmodel);
        }

        [HttpPost]
        public IActionResult Add(Models.Roles roles)
        {
            if (string.IsNullOrEmpty(roles.Name))
            {
                TempData["title"] = "Boş";
                return RedirectToAction("Index");
            }
            else
            {
                using (SqlConnection sqlconnection = new SqlConnection(connection))
                {
                    sqlconnection.Open();

                    var name = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(roles.Name);

                    string query = "INSERT INTO Roles VALUES ('"+ name +"')";

                    SqlCommand sqlCommand = new SqlCommand(query,sqlconnection);

                    sqlCommand.ExecuteNonQuery();
                }
            }
            TempData["title"] = "Başarılı";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            using (SqlConnection sqlconnection = new SqlConnection(connection))
            {
                sqlconnection.Open();

                string query = "DELETE FROM Roles WHERE Id = '"+id+"'";

                SqlCommand sqlCommand = new SqlCommand(query,sqlconnection);

                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
    }
}

HRS/HRS/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using HRS.Models;
using System.Globalization;

namespace HRS.Controllers
{
    public class WorkersController : Controller
    {
        private string _connection = @"Data Source = HP\SQLEXPRESS; Initial Catalog = HRS; User ID = sa; Password = 123456; Integrated Security = True";

        HRS.DataContext.HrsContext hrsContext = new DataContext.HrsContext();
        public IActionResult Index()
        {
            var viewmodel = new HRS.ViewModel.WorkersViewModel
            {
                WokerAndRoles = hrsContext.GetWokerAndRoles()
            };
            return View(viewmodel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var viewModel = new ViewModel.WorkersViewModel
            {
                Roles = Roles()
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Add(Models.Workers worker, string confirmPassword)
        {

            AddEdit(null, worker, confirmPassword);

            return RedirectToAction("Index");
        }

        private bool IsPasswordConfirm(string password1, string password2)
        {
            if (password1 != password2)
            {
                TempData["title"] = "Şifre Eşleşmiyor";
                return false;
            }
            else if (password1 == password2)
            {
                if (password1.Length < 6)
                {
                    return false;
                }
                return true;
            }
            return false;
        }

        private List<Roles> Roles()
        {
            var roles = new List<Models.Roles>();

            using (SqlConnection sqlconnection = new SqlConnection(_connection))
            {
                sqlconnection.Open();

                string query = "SELECT * FROM Roles";

                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                using (SqlDataReader sqlDataReader = sqlCommand.ExecuteReader())
                {
                    while (sqlDataReader.Read())
                    {
                        var role = new Roles();
                        role.Id = Convert.ToInt32(sqlDataReader["Id"]);
                        role.Name = sqlDataReader["Name"].ToString();

                        roles.Add(role);
                    }
                }
                sqlconnection.Close();
            }
            return roles;
        }

        private Workers AddEdit(int? id, Models.Workers worker, string confirmPassword)
        {
            string query;

            if (id.HasValue)
            { 
                //Düzenle
                query = "UPDATE Workers SET RoleId=@p1,Name=@p2,Surname=@p3,Gender=@p4,TcNo=@p5,DateOfBirth=@p6,Tel=@p7,Mail=@p8,UserName=@p9,Password=@p10 WHERE Id = " + id.Value + "";
            }
            else
            {
                //Ekleme
                query = "INSERT INTO Workers(RoleId,Name,Surname,Gender,TcNo,DateOfBirth,Tel,Mail,UserName,Password) VALUES (@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8,@p9,@p10)";
            }

            using (SqlConnection sqlconnection = new SqlConnection(_connection))
            {
                var pass = IsPasswordConfirm(worker.Password, confirmPassword);

                var name = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(worker.Name);
                var surname = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(worker.Surname);

                if (pass)
                {
                    sqlconnection.Open();

                    SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                    sqlCommand.Parameters.AddWithValue("@p1", worker.RoleId);
                    sqlCommand.Parameters.AddWithValue("@p2", name);
                    sqlCommand.Parameters.AddWithValue("@p3", surname);
                    sqlCommand.Parameters.AddWithValue("@p4", worker.Gender);
                    sqlCommand.Parameters.AddWithValue("@p5", worker.TcNo);
                    sqlCommand.Parameters.AddWithValue("@p6", worker.DateOfBirth);
                    sqlCommand.Parameters.AddWithValue("@p7", worker.Tel);
                    sqlCommand.Parameters.AddWithValue("@p8", worker.Mail);
                    sqlCommand.Parameters.AddWithValue("@p9", worker.UserName);
                    sqlCommand.Parameters.AddWithValue("@p10", worker.Password);

                    sqlCommand.ExecuteNonQuery();
                    sqlconnection.Close();
                }

            }
            return worker;
        }

        public IActionResult Delete(int id)
        {
            using (SqlConnection sqlconnection = new SqlConnection(_connection))
            {
                sqlconnection.Open();

                string query = "DELETE FROM Workers WHERE Id = '" + id + "'";

                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                sqlCommand.ExecuteNonQuery();
                sqlconnection.Close();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string workerid)
        {
            var viewModels = new ViewModel.WorkersViewModel
            {
                Roles = Roles()
            };

            using (SqlConnection sqlconnection = new SqlConnection(_connection))
            {
                sqlconnection.Open();

                string query = "SELECT R.Id,R.Name,W.Id,W.Name,W.Surname,W.Gender,W.TcNo,W.DateOfBirth,W.Tel,W.Mail,W.UserName,W.Password FROM Roles AS R  INNER JOIN Workers AS W On (R.Id=W.RoleId) WHERE W.Id = '" + workerid + "'";

                SqlCommand sqlCommand = new SqlCommand(query, sqlconnection);

                
                using (SqlDataReader sqlDataReader = sqlCommand.ExecuteReader())
                {
                    sqlDataReader.Read();
                    viewModels.RoleId = Convert.ToInt32(sqlDataReader[0].ToString());
                    viewModels.Id = Convert.ToInt32(sqlDataReader[2].ToString());
                    viewModels.Name = sqlDataReader[3].ToString();
                    viewModels.Surname = sqlDataReader[4].ToString();
                    viewModels.Gender = sqlDataReader[5].ToString();
                    viewModels.TcNo = sqlDataReader[6].ToString();
                    viewModels.DateOfBirth = DateTime.Parse(sqlDataReader[7].ToString());
                    viewModels.Tel = sqlDataReader[8].ToString();
                    viewModels.Mail = sqlDataReader[9].ToString();
                    viewModels.UserName = sqlDataReader[10].ToString();
                    viewModels.Password = sqlDataReader[11].ToString();
                }

                return View(viewModels);
            }
        }


        [HttpPost]
        public IActionResult Edit(Models.Workers worker, string confirmPassword)
        {
            AddEdit(worker.Id, worker, confirmPassword);

            return RedirectToAction("Index");
        }
    }
}

HRS/HRS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>@ViewData["title"] | HRS</title>
    <!-- css -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/css/plugins/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/plugins/iCheck/custom.css" rel="stylesheet" />
    <link href="~/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet" />

</head>
<body>

    <div id="wrapper">
        <!-- navbar -->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <img alt="image" class="rounded-circle" src="img/profile_small.jpg" />
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="block m-t-xs font-bold">Mustafa Furkan Cinoğlu</span>
                                <span class="text-muted text-xs block">Baş Hekim<b class="caret"></b></span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="dropdown-item" href="profile.html">Profile</a></li>
                                <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
                                <li><a class="dropdown-item" href="mailbox.html">Mailbox</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="login.html">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            HRS
                        </div>
                    </li>
                    <li class="active">
                        <a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i> <span class="nav-label">Anasayfa</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-user"></i> <span class="nav-label">Personel</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                                <a href="@Url.Action("Index","Workers")"><i class="fa fa-users"></i>İşçiler</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Doctors")"><i class="fa fa-user-md"></i>Doktor Ekle</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Roles")"><i class="fa fa-plus"></i>İşçi Grubu Ekle</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Clinic")"><i class="fa fa-hospital-o"></i><span class="nav-label">Klinik Ekle</span></a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Appointment")"><i class="fa fa-calendar" aria-hidden="true"></i><span class="nav-label">Randevu Tanımlama</span></a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","MakeAnAppointment")"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i><span class="nav-label">Randevu Al</span></a>
                    </li>
                    <li class="special_link">
                        <a href="#"><i class="fa fa-sign-out"></i> <span class="nav-label">Çıkış</span></a>
                    </li>
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">

            <!-- topbar -->
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="http://webapplayers.com/inspinia_admin-v2.9.2/search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li style="padding: 20px">
                            <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                            </a>
                            <ul class="dropdown-menu dropdown-messages dropdown-menu-right">
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/a7.jpg">
                                        </a>
                                        <div class="media-body">
                                            <small class="float-right">46h ago</small>
                                            <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                            <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/a4.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="float-right text-navy">5h ago</small>
                                            <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                            <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a class="dropdown-item float-left" href="profile.html">
                                            <img alt="image" class="rounded-circle" src="img/profile.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="float-right">23h ago</small>
                                            <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                            <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a href="mailbox.html" class="dropdown-item">
                                            <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="mailbox.html" class="dropdown-item">
                                        <div>
                                            <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                            <span class="float-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <a href="profile.html" class="dropdown-item">
                                        <div>
                                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                            <span class="float-right text-muted small">12 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <a href="grid_options.html" class="dropdown-item">
                                        <div>
                                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                            <span class="float-right text-muted small">4 minutes ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a href="notifications.html" class="dropdown-item">
                                            <strong>See All Alerts</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>


                        <li>
                            <a href="login.html">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                        <li>
                            <a class="right-sidebar-toggle">
                                <i class="fa fa-tasks"></i>
                            </a>
                        </li>
                    </ul>

                </nav>
            </div>

            @RenderBody()

            <div class="footer">
                <div>
                    <strong>Copyright</strong> HRS &copy; 2019
                </div>
            </div>
        </div>
    </div>





    <!-- Mainly scripts -->
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Flot -->
    <script src="~/js/plugins/flot/jquery.flot.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.spline.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.resize.js"></script>
    <script src="~/js/plugins/flot/jquery.flot.pie.js"></script>

    <!-- Peity -->
    <script src="~/js/plugins/peity/jquery.peity.min.js"></script>
    <script src="~/js/demo/peity-demo.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/js/inspinia.js"></script>
    <script src="~/js/plugins/pace/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="~/js/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- GITTER -->
    <script src="js/plugins/gritter/jquery.gritter.min.js"></script>

    <!-- Sparkline -->
    <script src="~/js/plugins/sparkline/jquery.sparkline.min.js"></script>

    <!-- Sparkline demo data  -->
    <script src="~/js/demo/sparkline-demo.js"></script>

    <!-- ChartJS-->
    <script src="~/js/plugins/chartJs/Chart.min.js"></script>

    <!-- Toastr -->
    <script src="~/js/plugins/toastr/toastr.min.js"></script>

    <script src="~/hrs.js"></script>
</body>
</html>